### PR TITLE
C2C-305: Add openmrs, bahmni and odoo configs locally and fix pom.xml

### PR DESCRIPTION
**Pull request by VaishSiddharth**
JIRA: https://mekomsolutions.atlassian.net/browse/C2C-305

### CODE REVIEW

**Comment by rbuisson** [comment]
@VaishSiddharth , let me correct myself, let's rework the structure to be:
```
configs/
|-- openmrs/
|-- odoo/
|-- bahmni/
```

**Comment by VaishSiddharth** [comment]
@rbuisson have fixed the structure and tested master and this branch build (target) folders with `diff -qr` command
Only difference is in `SNAPSHOT.zip` folders that must be because the command cannot find whats inside the zip folder.
Also the folder naming is a bit different 
```
configs/
|-- openmrs_config/
|-- odoo_config/
|-- bahmni_config/
```

**Comment by VaishSiddharth** [comment]
Only these files/folder differ

```
Files new/target/bahmni-distro-haiti-3.0.0-SNAPSHOT.zip and old/target/bahmni-distro-haiti-3.0.0-SNAPSHOT.zip differ
Only in old/target/dependency-maven-plugin-markers: net.mekomsolutions-bahmni-config-haiti-zip-2.0.0-SNAPSHOT.marker
Only in old/target/dependency-maven-plugin-markers: net.mekomsolutions-odoo-config-haiti-zip-2.4.0-SNAPSHOT.marker
Only in old/target/dependency-maven-plugin-markers: net.mekomsolutions-openmrs-config-haiti-zip-2.2.0-SNAPSHOT.marker
```

**Review by Ruhanga — CHANGES_REQUESTED** [review]
Some pending cleanup below:
[These](https://github.com/mekomsolutions/bahmni-distro-haiti/pull/30/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R500-R529) will have to go. [These](https://github.com/mekomsolutions/bahmni-distro-haiti/pull/30/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R38-R40) too. I guess these will help resolve the issues on the child C2C distro.

**Review by Ruhanga — APPROVED** [review]
LGTM

**Pull request merged**
