### PR TITLE
INFRA-338: Use Github Actions

### PR DESCRIPTION
**Pull request by chinzou**
https://mekomsolutions.atlassian.net/browse/MSF-22

### CODE REVIEW

**Comment by rbuisson** [comment]
@chinzou , is this on the right repo?
Ticket number suggests this is

**Comment by rbuisson** [comment]
@chinzou , is this related to INFRA-338? Which suggests to migrate Odoo Addons builds to GitHub Actions, not so much the distros.

**Comment by chinzou** [comment]
That's actually not really part of the Odoo migration. but more of an attempt to switch to Github Actions since the `.travis` file is there without being used.

**Comment by chinzou** [comment]
Feel free to close if this is not needed. It's not really part of the **INFRA-338**  ticket

**Pull request closed without merging**
